/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
/* eslint-disable @typescript-eslint/explicit-function-return-type */
'use client'
import "bootstrap/dist/css/bootstrap.min.css";
import './globals.css';
import { useEffect } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    //@ts-expect-error
    import("bootstrap/dist/js/bootstrap.bundle.min.js")
  })

  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
